#!/bin/sh

#common
WRCPUUTIL=/usr/bin/partool
if [ -d /jffs/.OEM ];then
	PATHVENDOR=/jffs/.OEM
	if [ ! -f /jffs/.OEM/.company_name ];then
		COMPANY_NAME="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.vendor/{print $2}'`"
		PRODUCT_TYPE="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.model/{print $2}'`"
		SERIAL_NUMBER="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.sn/{print $2}'`"
		MAC="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.mac/{print $2}'`"
#		SOFT_VERSION="`cat /etc/version/version`#`cat /etc/version/buildno`"
		SOFT_VERSION=1.3
		MAIN_VER="`echo $SERIAL_NUMBER | cut -b 10`"
		MINOR_VER="`echo $SERIAL_NUMBER | cut -b 11-12`"
		HARD_VERSION="$MAIN_VER.$MINOR_VER"
#		HARD_VERSION=2.0
	else
		COMPANY_NAME="`cat $PATHVENDOR/.company_name`"
		if [ -f /jffs/.OEM/.product_name ];then
			PRODUCT_TYPE="`cat $PATHVENDOR/.product_name`"
		else
			PRODUCT_TYPE="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.model/{print $2}'`"
		fi
		if [ -f /jffs/.OEM/.sn ];then
			SERIAL_NUMBER="`cat $PATHVENDOR/.sn`"
		else
			SERIAL_NUMBER="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.sn/{print $2}'`"
		fi
		if [ -f /jffs/.OEM/.mac_eth0 ];then
#			MAC=`cat $PATHVENDOR/.mac_eth0`
			temp_mac="`cat $PATHVENDOR/.mac_eth0`"
			MAC="`/sbin/set_mac org $temp_mac`"
		else
			MAC="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.mac/{print $2}'`"
		fi
		if [ -f /jffs/.OEM/.software_version ];then
			if [ -f /jffs/.OEM/.build_no ];then
				SOFT_VERSION="`cat $PATHVENDOR/.software_version`#`cat $PATHVENDOR/.build_no`"
			else
				SOFT_VERSION="`cat $PATHVENDOR/.software_version`"
			fi
		else
#			SOFT_VERSION="`cat /etc/version/version`#`cat /etc/version/buildno`"
			SOFT_VERSION=1.3
		fi
		if [ -f /jffs/.OEM/.hardware_version ];then
			HARD_VERSION="`cat $PATHVENDOR/.hardware_version`"
		else
			MAIN_VER="`echo $SERIAL_NUMBER | cut -b 10`"
			MINOR_VER="`echo $SERIAL_NUMBER | cut -b 11-12`"
			HARD_VERSION="$MAIN_VER.$MINOR_VER"
#			HARD_VERSION=2.0
		fi
	fi
else
	COMPANY_NAME="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.vendor/{print $2}'`"
	PRODUCT_TYPE="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.model/{print $2}'`"
	SERIAL_NUMBER="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.sn/{print $2}'`"
	MAC="`$WRCPUUTIL -part mtd8 -show |awk -F'=' '/product.mac/{print $2}'`"
#	SERIAL_NUMBER=${MAC}
#	SOFT_VERSION="`cat /etc/version/version`#`cat /etc/version/buildno`"
	SOFT_VERSION=1.3
	MAIN_VER="`echo $SERIAL_NUMBER | cut -b 10`"
	MINOR_VER="`echo $SERIAL_NUMBER | cut -b 11-12`"
	HARD_VERSION="$MAIN_VER.$MINOR_VER"
#	HARD_VERSION=2.0
fi

#show
echo "    Company Name:$COMPANY_NAME"
echo "              SN:$SERIAL_NUMBER"
echo "         Ap Mode:fatap"
echo "     Device Type:$PRODUCT_TYPE"
echo "             MAC:$MAC"

if [ -f /jffs/.OEM/.software_version ];then
	if [ -f /jffs/.OEM/.build_no ];then
		SOFT_VERSION="`cat $PATHVENDOR/.software_version`#`cat $PATHVENDOR/.build_no`"
	else
		SOFT_VERSION="`cat $PATHVENDOR/.software_version`"
	fi
fi
if [ -f /jffs/.OEM/.hardware_version ];then
	HARD_VERSION="`cat $PATHVENDOR/.hardware_version`"
fi

echo "Software Version:$SOFT_VERSION"
echo "Hardware Version:$HARD_VERSION"
