#!/bin/sh /etc/rc.common

START=75

USE_PROCD=1
PROG=/usr/bin/cfpd

start_service()
{
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "cfpd"
}
