#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	# allow wifi modules time to settle
	sleep 1

	/sbin/wifi detect > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		cat /tmp/wireless.tmp >> /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	uci_apply_defaults

	# temporary hack until configd exists
	/sbin/reload_config

	#zhouke add for version differentiation
	echo thin-ac > /tmp/sysinfo/osinfo
	
	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	#add by zhouke mount mtdblock5 to jffs
	mount -rw -t jffs2 /dev/mtdblock5 /jffs

	#add by liwei to count restart number                                                       
	local count="`/sbin/uci get system.record.boot_count`" > /dev/null 2>&1
	if [ x"$count" == x ]; then
		/sbin/uci set system.record=extend
		/sbin/uci set system.record.boot_count=1                                            

		#add by chenxf check if we need to recover configuration from oldos
		/etc/wlan/config_recover
		
		#add by zhouke to AE500_E2X2 product info transplant when first boot
		/sbin/product_transplant 1
	else
		/sbin/uci set system.record.boot_count=$((count+1))
	fi
	
	#add by wangjianru for hostname
	local hostname="$(/usr/sbin/showsysinfo|/bin/grep 'Company Name:'|/usr/bin/cut -d: -f2)"
	#echo "$hostname" > /proc/sys/kernel/hostname
	uci set system.@system[0].hostname="$hostname"
	uci commit system

	#add by wangjianru for update eth macaddr
	local mac="$(/usr/sbin/showsysinfo|/bin/grep 'MAC:'|/usr/bin/cut -d: -f2-7)"
	ifconfig eth0 down
	ifconfig eth0 hw ether "$mac"
	ifconfig eth0 up

	#add by zhouke to AE5000_E2X2 mac address policy
	touch /jffs/.mac-policy

    #add by chenxf for start kes service
	/etc/wlan/config_kes

    #add by chenxf for set ap workmode
	#local workmode="`/sbin/uci get system.runmode.ap_mode`"
	local workmode=$(cat /tmp/sysinfo/osinfo)
	if [ $workmode = "thin-ac" ]; then
		echo 1 > /proc/sys/dev/wifi0/thinap
	elif [ $workmode = "fat-ac" ]; then
		echo 0 > /proc/sys/dev/wifi0/thinap
	fi
	
    #added by duanmingzhe disable or enable uplink-interface
	#AP_MODE="$(/sbin/uci get system.runmode.ap_mode)" > /dev/null 2>&1
	if [ "thin-ac" != "$workmode" ] && [ "fat-ac" != "$workmode" ]; then
		/sbin/uci set wireless.@wifi-iface[0].disabled=0
	else  #else mode is "fat-afc" and "cloud-afc"
		/sbin/uci set wireless.@wifi-iface[0].disabled=1
	fi
	/sbin/uci commit wireless
	
}
